// src/pages/ResumePage.jsx
import { motion } from 'framer-motion';
import { 
  Mail, 
  Globe, 
  Github, 
  GraduationCap, 
  Printer, 
  Download, 
  MapPin, 
  Phone, 
  Linkedin, 
  User, 
  Languages, 
  Award, 
  Briefcase, 
  BookOpen, 
  Target,
  Users,
  MessageSquare,
  TrendingUp,
  Lightbulb,
  Code,
  Palette,
  Database,
  Smartphone,
  Monitor,
  Zap
} from 'lucide-react';
import WhatsAppIcon from '../components/ui/WhatsAppIcon';

const ResumePage = () => {
  const contactInfo = [
    { icon: Mail, label: 'rahmanhamad36@gmail.com', href: 'mailto:rahmanhamad36@gmail.com' },
    { icon: Phone, label: '+234 812 911 7778', href: 'tel:+2348129117778' },
    { icon: WhatsAppIcon, label: 'WhatsApp', href: 'https://wa.me/2348129117778' },
    { icon: MapPin, label: 'Remote Worldwide', href: null },
    { icon: Linkedin, label: 'linkedin.com/in/al-ahmodany', href: 'https://linkedin.com/in/al-ahmodany' },
    { icon: Globe, label: 'al-ahmodany.dev', href: 'https://al-ahmodany.dev' },
  ];

  const languages = [
    { name: 'English', level: 5 },
    { name: 'Arabic', level: 5 },
  ];

  const awards = [
    {
      title: 'Outstanding Frontend Developer',
      institution: 'Freelance Client Recognition',
      year: '2024'
    },
    {
      title: 'Best UI Implementation',
      institution: 'E-commerce Project Excellence',
      year: '2023'
    }
  ];

  const workExperience = [
    {
      company: 'Freelance',
      position: 'Frontend Developer',
      period: '2023 – present',
      location: 'Remote',
      achievements: [
        'Developed and implemented strategic React applications resulting in a 40% increase in client satisfaction.',
        'Collaborated with cross-functional teams to drive business growth and user engagement.',
        'Established and maintained strong client relationships with key partners resulting in a 35% increase in project revenue.',
        'Conducted market research and analysis to identify new opportunities resulting in the successful launch of 7+ live projects.'
      ]
    },
    {
      company: 'Self-Directed Learning',
      position: 'Frontend Developer',
      period: '2021 – 2023',
      location: 'Remote',
      achievements: [
        'Worked closely with modern web technologies to provide expert development services',
        'Built and managed dedicated learning path in React, JavaScript, and modern CSS frameworks',
        'Contributed to open-source projects with proven track record of success in acting as an individual contributor to the development of 15+ personal projects and innovative solutions since 2021.'
      ]
    }
  ];

  const education = [
    {
      degree: 'Self-Directed Frontend Development',
      school: 'Online Learning Platforms',
      period: '2021 – 2024',
      location: 'Remote'
    },
    {
      degree: 'Advanced React Development',
      school: 'Udemy & freeCodeCamp',
      period: '2022 – 2023',
      location: 'Online'
    }
  ];

  const skills = [
    'Strategic thinking and problem-solving',
    'Component architecture and design patterns',
    'Effective communication and client relations',
    'Modern JavaScript and React development strategy',
    'Team collaboration and project leadership',
    'Creative and innovative UI/UX thinking'
  ];

  const printCV = () => {
    window.print();
  };

  return (
    <div className="pt-28">
      <section className="section-padding max-w-6xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="flex flex-col md:flex-row items-start md:items-center justify-between mb-12 gap-6"
        >
          <div>
            <span className="tag">Resume</span>
            <h1 className="font-display font-extrabold text-5xl md:text-7xl mt-4 leading-none">
              My <span className="text-gradient">CV</span>
            </h1>
          </div>
          <div className="flex gap-3 flex-wrap">
            <button onClick={printCV} className="btn-primary">
              <Printer size={16} /> Print or Save PDF
            </button>
            <a href="/cv.pdf" download="AL-AHMODANY-CV.pdf" className="btn-outline">
              <Download size={16} /> Download CV
            </a>
            <a href="https://github.com/AL-AHMODANY" target="_blank" rel="noreferrer" className="btn-outline">
              <Github size={16} /> GitHub
            </a>
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          id="resume-content" 
          className="bg-white dark:bg-gray-900 rounded-3xl overflow-hidden shadow-2xl"
        >
          <div className="grid lg:grid-cols-5 min-h-[800px]">
            {/* Left Sidebar - Dark */}
            <div className="lg:col-span-2 bg-slate-700 dark:bg-slate-800 text-white p-8">
              {/* Header */}
              <div className="text-center mb-8">
                <h1 className="font-display font-bold text-3xl mb-2">AL-AHMODANY</h1>
                <p className="text-slate-300 text-lg">Frontend Developer</p>
                <p className="text-slate-300 text-sm">React Specialist</p>
              </div>

              {/* Profile Image Placeholder */}
              <div className="w-32 h-32 mx-auto mb-8 rounded-full bg-slate-600 flex items-center justify-center">
                <User size={48} className="text-slate-300" />
              </div>

              {/* Contact Info */}
              <div className="mb-8">
                <div className="flex items-center gap-2 mb-4">
                  <Mail size={16} />
                  <h3 className="font-semibold text-sm uppercase tracking-wider">Contact</h3>
                </div>
                <div className="space-y-3">
                  {contactInfo.map((contact, index) => (
                    <div key={index} className="flex items-start gap-3">
                      <contact.icon 
                        size={14} 
                        className={`mt-0.5 flex-shrink-0 ${
                          contact.label === 'WhatsApp' 
                            ? 'text-[#25D366]' 
                            : 'text-slate-300'
                        }`} 
                      />
                      {contact.href ? (
                        <a 
                          href={contact.href} 
                          className={`text-sm transition-colors ${
                            contact.label === 'WhatsApp' 
                              ? 'text-[#25D366] hover:text-[#128C7E]' 
                              : 'text-slate-300 hover:text-white'
                          }`}
                          target={contact.href.startsWith('http') ? '_blank' : undefined}
                          rel={contact.href.startsWith('http') ? 'noreferrer' : undefined}
                        >
                          {contact.label}
                        </a>
                      ) : (
                        <span className="text-slate-300 text-sm">{contact.label}</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Profile */}
              <div className="mb-8">
                <div className="flex items-center gap-2 mb-4">
                  <User size={16} />
                  <h3 className="font-semibold text-sm uppercase tracking-wider">Profile</h3>
                </div>
                <p className="text-slate-300 text-sm leading-relaxed">
                  I'm AL-AHMODANY, a frontend developer with a passion for creating exceptional user experiences. 
                  With expertise in React and modern web technologies, I strive to build innovative solutions that 
                  drive success for my clients. My focus is on clean code, responsive design, and delivering 
                  high-quality applications that exceed expectations.
                </p>
              </div>

              {/* Languages */}
              <div className="mb-8">
                <div className="flex items-center gap-2 mb-4">
                  <Languages size={16} />
                  <h3 className="font-semibold text-sm uppercase tracking-wider">Languages</h3>
                </div>
                <div className="space-y-3">
                  {languages.map((lang, index) => (
                    <div key={index}>
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-slate-300 text-sm">{lang.name}</span>
                      </div>
                      <div className="flex gap-1">
                        {[...Array(5)].map((_, i) => (
                          <div 
                            key={i} 
                            className={`w-3 h-3 rounded-full ${
                              i < lang.level ? 'bg-accent' : 'bg-slate-600'
                            }`}
                          />
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Awards */}
              <div>
                <div className="flex items-center gap-2 mb-4">
                  <Award size={16} />
                  <h3 className="font-semibold text-sm uppercase tracking-wider">Awards</h3>
                </div>
                <div className="space-y-4">
                  {awards.map((award, index) => (
                    <div key={index}>
                      <h4 className="text-white text-sm font-semibold">{award.title}</h4>
                      <p className="text-slate-300 text-xs">{award.institution}</p>
                      <p className="text-slate-400 text-xs">{award.year}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Right Content - Light */}
            <div className="lg:col-span-3 p-8 bg-gray-50 dark:bg-gray-800">
              {/* Work Experience */}
              <div className="mb-10">
                <div className="flex items-center gap-2 mb-6">
                  <Briefcase size={20} className="text-gray-700 dark:text-gray-300" />
                  <h2 className="font-bold text-xl text-gray-800 dark:text-gray-200 uppercase tracking-wider">Work Experience</h2>
                </div>
                
                <div className="space-y-8">
                  {workExperience.map((job, index) => (
                    <div key={index} className="relative">
                      <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-sm">
                        <div className="flex flex-col md:flex-row md:items-start md:justify-between mb-2">
                          <div>
                            <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">{job.company}</h3>
                            <p className="text-gray-600 dark:text-gray-400 font-medium">{job.position}</p>
                          </div>
                          <div className="text-right">
                            <p className="text-sm font-medium text-gray-700 dark:text-gray-300">{job.period}</p>
                            <p className="text-sm text-gray-500 dark:text-gray-400">{job.location}</p>
                          </div>
                        </div>
                        <ul className="space-y-2 mt-4">
                          {job.achievements.map((achievement, i) => (
                            <li key={i} className="text-sm text-gray-600 dark:text-gray-400 flex items-start gap-2">
                              <span className="text-accent mt-1 flex-shrink-0">•</span>
                              {achievement}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Education */}
              <div className="mb-10">
                <div className="flex items-center gap-2 mb-6">
                  <BookOpen size={20} className="text-gray-700 dark:text-gray-300" />
                  <h2 className="font-bold text-xl text-gray-800 dark:text-gray-200 uppercase tracking-wider">Education</h2>
                </div>
                
                <div className="space-y-6">
                  {education.map((edu, index) => (
                    <div key={index} className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-sm">
                      <div className="flex flex-col md:flex-row md:items-start md:justify-between">
                        <div>
                          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">{edu.degree}</h3>
                          <p className="text-gray-600 dark:text-gray-400 font-medium">{edu.school}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-sm font-medium text-gray-700 dark:text-gray-300">{edu.period}</p>
                          <p className="text-sm text-gray-500 dark:text-gray-400">{edu.location}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Skills */}
              <div>
                <div className="flex items-center gap-2 mb-6">
                  <Target size={20} className="text-gray-700 dark:text-gray-300" />
                  <h2 className="font-bold text-xl text-gray-800 dark:text-gray-200 uppercase tracking-wider">Skills</h2>
                </div>
                
                <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-sm">
                  <ul className="space-y-3">
                    {skills.map((skill, index) => (
                      <li key={index} className="text-sm text-gray-600 dark:text-gray-400 flex items-start gap-2">
                        <span className="text-accent mt-1 flex-shrink-0">•</span>
                        {skill}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </section>
    </div>
  );
};

export default ResumePage;

// src/pages/ResumePage.vue
<template>
  <div class="pt-28">
    <section class="section-padding max-w-5xl mx-auto">
      <div class="flex flex-col md:flex-row items-start md:items-center justify-between mb-12 reveal gap-6">
        <div>
          <span class="tag">Resume</span>
          <h1 class="font-display font-extrabold text-5xl md:text-7xl mt-4 leading-none">
            My <span class="text-gradient">CV</span>
          </h1>
        </div>
        <div class="flex gap-3 flex-wrap">
          <button @click="printCV" class="btn-primary">
            <Printer :size="16" /> Print or Save PDF
          </button>
          <a href="/AL-AHMODANY-CV.html" target="_blank" class="btn-outline">
            <Download :size="16" /> Download CV
          </a>
          <a href="https://github.com/AL-AHMODANY" target="_blank" rel="noreferrer" class="btn-outline">
            <Github :size="16" /> GitHub
          </a>
        </div>
      </div>

      <div id="resume-content" class="card-glass rounded-3xl overflow-hidden shadow-2xl">
        <div class="bg-gradient-to-r from-accent/20 via-emerald-600/10 to-blue-500/10 p-10 border-b border-[var(--border)] relative overflow-hidden">
          <div class="absolute inset-0 grid-pattern opacity-30"></div>
          <div class="relative z-10 flex flex-col md:flex-row items-start md:items-center gap-6">
            <div class="relative w-20 h-20 flex-shrink-0">
              <div class="absolute inset-0 rounded-full resume-ring"></div>
              <div class="absolute inset-1 rounded-full bg-gradient-to-br from-accent/30 to-emerald-600/30 flex items-center justify-center border border-accent/30">
                <span class="font-display font-black text-xl text-gradient">AL</span>
              </div>
            </div>
            <div class="flex-1">
              <h2 class="font-display font-black text-3xl">AL-AHMODANY</h2>
              <p class="text-accent font-mono text-sm mt-1">Frontend Developer - Vue.js Specialist - UI Engineer</p>
              <div class="flex flex-wrap gap-x-6 gap-y-2 mt-3 text-sm text-[var(--muted)]">
                <span class="flex items-center gap-1.5"><Mail :size="13" /> contact@al-ahmodany.dev</span>
                <span class="flex items-center gap-1.5"><Globe :size="13" /> al-ahmodany.dev</span>
                <span class="flex items-center gap-1.5"><Github :size="13" /> github.com/al-ahmodany</span>
                <span class="flex items-center gap-1.5 text-accent font-bold">
                  <span class="w-2 h-2 rounded-full bg-accent animate-pulse"></span> Available for work
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="p-8 md:p-10 grid md:grid-cols-3 gap-10">
          <div class="space-y-8">
            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Core Skills
              </h3>
              <div class="space-y-3">
                <div v-for="skill in topSkills" :key="skill.name">
                  <div class="flex justify-between text-xs mb-1.5">
                    <span class="font-mono">{{ skill.name }}</span>
                    <span class="text-accent">{{ skill.level }}%</span>
                  </div>
                  <div class="h-1.5 rounded-full bg-[var(--border)]">
                    <div class="h-full rounded-full bg-gradient-to-r from-accent to-emerald-400" :style="`width: ${skill.level}%`"></div>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Tools
              </h3>
              <div class="flex flex-wrap gap-2">
                <span v-for="tool in toolsList" :key="tool" class="tag text-xs">{{ tool }}</span>
              </div>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Languages
              </h3>
              <div class="space-y-2">
                <div class="flex justify-between items-center">
                  <span class="text-sm font-body">Arabic</span>
                  <span class="text-accent text-xs font-mono bg-accent/10 px-2 py-0.5 rounded-full border border-accent/20">Native</span>
                </div>
                <div class="flex justify-between items-center">
                  <span class="text-sm font-body">English</span>
                  <span class="text-accent text-xs font-mono bg-accent/10 px-2 py-0.5 rounded-full border border-accent/20">Fluent</span>
                </div>
              </div>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Strengths
              </h3>
              <ul class="space-y-2">
                <li v-for="skill in softSkills" :key="skill" class="flex items-center gap-2 text-sm text-[var(--muted)]">
                  <span class="text-accent flex-shrink-0">›</span> {{ skill }}
                </li>
              </ul>
            </div>
          </div>

          <div class="md:col-span-2 space-y-10">
            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Professional Summary
              </h3>
              <p class="text-[var(--muted)] leading-relaxed text-sm">
                Frontend developer with hands-on experience building Vue.js interfaces for live products across e-commerce,
                community platforms, dashboards, and utility applications. Strong focus on maintainable component architecture,
                responsive design, user experience quality, and shipping clean interfaces that feel finished in production.
              </p>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-6 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Experience
              </h3>
              <div class="space-y-7">
                <div
                  v-for="experienceItem in experience"
                  :key="experienceItem.title"
                  class="border-l-2 border-accent/20 pl-5 hover:border-accent transition-colors duration-300 group"
                >
                  <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-1 gap-2">
                    <h4 class="font-display font-semibold group-hover:text-accent transition-colors">{{ experienceItem.title }}</h4>
                    <span class="text-xs font-mono text-accent bg-accent/10 px-2 py-0.5 rounded-full border border-accent/20 whitespace-nowrap">
                      {{ experienceItem.period }}
                    </span>
                  </div>
                  <p class="text-accent font-mono text-xs mb-3">{{ experienceItem.company }}</p>
                  <ul class="space-y-1.5">
                    <li v-for="point in experienceItem.points" :key="point" class="text-[var(--muted)] text-sm flex gap-2">
                      <span class="text-accent mt-1 flex-shrink-0">›</span>{{ point }}
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-6 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Education and Certifications
              </h3>
              <div class="space-y-4">
                <div v-for="edu in education" :key="edu.title" class="flex gap-4 group">
                  <div class="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center flex-shrink-0 group-hover:bg-accent/20 transition-colors">
                    <GraduationCap :size="18" class="text-accent" />
                  </div>
                  <div>
                    <h4 class="font-display font-semibold text-sm group-hover:text-accent transition-colors">{{ edu.title }}</h4>
                    <p class="text-[var(--muted)] text-xs">{{ edu.institution }}</p>
                    <p class="text-accent font-mono text-xs mt-0.5">{{ edu.year }}</p>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h3 class="font-display font-bold text-lg mb-4 flex items-center gap-2">
                <span class="w-1 h-5 bg-accent rounded-full"></span> Key Projects
              </h3>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <a
                  v-for="project in keyProjects"
                  :key="project.name"
                  :href="project.url"
                  target="_blank"
                  rel="noreferrer"
                  class="p-3 rounded-xl border border-[var(--border)] hover:border-accent/40 hover:bg-accent/5 transition-all duration-300 group"
                >
                  <p class="font-display font-semibold text-sm group-hover:text-accent transition-colors">{{ project.name }}</p>
                  <p class="text-[var(--muted)] text-xs mt-0.5 font-mono">{{ project.stack }}</p>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { Mail, Globe, Github, GraduationCap, Printer, Download } from 'lucide-vue-next'

const topSkills = [
  { name: 'Vue.js 3', level: 92 },
  { name: 'JavaScript (ES6+)', level: 90 },
  { name: 'Tailwind CSS', level: 95 },
  { name: 'HTML5 / CSS3', level: 98 },
  { name: 'Firebase / REST APIs', level: 80 },
]

const toolsList = ['Vite', 'Git', 'Figma', 'VS Code', 'Vercel', 'Postman', 'Pinia', 'Vue Router']

const softSkills = [
  'Design-aware UI implementation',
  'Clear communication and collaboration',
  'Reliable delivery under deadlines',
  'Frontend architecture with reuse in mind',
  'Fast iteration without losing quality',
]

const experience = [
  {
    title: 'Frontend Developer',
    company: 'Freelance - Remote',
    period: '2023 - Present',
    points: [
      'Built and shipped live Vue.js products for client-facing use cases across multiple industries.',
      'Created responsive interfaces for e-commerce, dashboards, and community platforms with clean component structure.',
      'Integrated frontend applications with Firebase, routing, and practical API-driven UI flows.',
      'Focused on performance, readability, and polished interaction details throughout delivery.',
    ],
  },
  {
    title: 'Frontend Builder',
    company: 'Independent Learning and Product Practice',
    period: '2021 - 2023',
    points: [
      'Developed hands-on expertise through personal products, iterative redesigns, and real interface problem solving.',
      'Built confidence in JavaScript, Vue, layout systems, and frontend architecture through constant project work.',
      'Studied modern frontend workflows through official docs, structured courses, and repeated practice.',
    ],
  },
]

const education = [
  { title: 'Self-Directed Frontend Study', institution: 'MDN, Vue Docs, freeCodeCamp, Udemy', year: '2021 - Present' },
  { title: 'Vue.js 3 Course Work', institution: 'Udemy', year: '2022' },
  { title: 'JavaScript and Web Fundamentals', institution: 'freeCodeCamp and practical projects', year: '2021' },
]

const keyProjects = [
  { name: 'Nour Zamon E-Commerce', stack: 'Vue 3 - Pinia - Tailwind', url: 'https://nourzamon-ecommerce.vercel.app/' },
  { name: 'Morkaznourzaman Platform', stack: 'Vue 3 - Firebase - JavaScript', url: 'https://morkaznourzaman.vercel.app/' },
  { name: 'Weather App', stack: 'Vue 3 - OpenWeather API', url: 'https://weather-app-woad-rho-47.vercel.app/' },
  { name: 'Larkon Productivity App', stack: 'Vue 3 - Pinia - Firebase', url: 'https://larkon-app.vercel.app/' },
]

function printCV() {
  window.print()
}
</script>

<style scoped>
.resume-ring {
  background: conic-gradient(from 0deg, #00FF94, transparent, transparent, #00FF94);
  animation: rotateBorder 4s linear infinite;
  border-radius: 50%;
}

@keyframes rotateBorder {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
</style>

<style>
@media print {
  header,
  footer,
  button,
  .btn-primary,
  .btn-outline {
    display: none !important;
  }

  body {
    background: white !important;
    color: black !important;
  }

  #resume-content {
    box-shadow: none !important;
    border: 1px solid #eee !important;
  }
}
</style>
