// src/App.jsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { ThemeProvider } from './contexts/ThemeContext';
import { useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';

// Layout Components
import NavBar from './components/layout/NavBar';
import Footer from './components/layout/Footer';
import ScrollToTop from './components/ui/ScrollToTop';
import WhatsAppButton from './components/ui/WhatsAppButton';

// Pages
import HomePage from './pages/HomePage';
import AboutPage from './pages/AboutPage';
import ProjectsPage from './pages/ProjectsPage';
import SkillsPage from './pages/SkillsPage';
import ResumePage from './pages/ResumePage';
import ContactPage from './pages/ContactPage';
import NotFoundPage from './pages/NotFoundPage';

// Reveal Animation Hook
const useRevealAnimation = () => {
  const location = useLocation();

  useEffect(() => {
    const observeRevealElements = () => {
      const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('visible');
            observer.unobserve(entry.target);
          }
        });
      }, { threshold: 0.1 });

      document.querySelectorAll('.reveal').forEach((el) => {
        if (!el.classList.contains('visible')) {
          observer.observe(el);
        }
      });

      return observer;
    };

    const timer = setTimeout(() => {
      observeRevealElements();
    }, 100);

    return () => clearTimeout(timer);
  }, [location.pathname]);
};

// Cursor Glow Effect
const CursorGlow = () => {
  const cursorRef = useRef(null);

  useEffect(() => {
    const handleMouseMove = (e) => {
      if (cursorRef.current) {
        cursorRef.current.style.left = e.clientX + 'px';
        cursorRef.current.style.top = e.clientY + 'px';
      }
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  return <div ref={cursorRef} className="cursor-glow hidden lg:block" />;
};

// App Layout Component
const AppLayout = () => {
  useRevealAnimation();

  return (
    <div className="min-h-screen">
      <CursorGlow />
      <NavBar />
      <main>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/about" element={<AboutPage />} />
          <Route path="/projects" element={<ProjectsPage />} />
          <Route path="/skills" element={<SkillsPage />} />
          <Route path="/resume" element={<ResumePage />} />
          <Route path="/contact" element={<ContactPage />} />
          <Route path="*" element={<NotFoundPage />} />
        </Routes>
      </main>
      <Footer />
      <ScrollToTop />
      <WhatsAppButton />
    </div>
  );
};

function App() {
  return (
    <ThemeProvider>
      <Router>
        <AppLayout />
      </Router>
    </ThemeProvider>
  );
}

export default App;

// src/App.vue
<template>
  <div class="min-h-screen" :class="{ dark: isDark }">
    <div class="cursor-glow hidden lg:block" ref="cursorGlow"></div>
    <NavBar />
    <main>
      <router-view v-slot="{ Component }">
        <transition name="page" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </main>
    <FooterSection />
    <ScrollToTop />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useThemeStore } from './stores/theme.js'
import NavBar from './components/layout/NavBar.vue'
import FooterSection from './components/layout/FooterSection.vue'
import ScrollToTop from './components/ui/ScrollToTop.vue'

const themeStore = useThemeStore()
const isDark = computed(() => themeStore.isDark)
const cursorGlow = ref(null)
const route = useRoute()
let observer = null

function handleMouseMove(e) {
  if (cursorGlow.value) {
    cursorGlow.value.style.left = e.clientX + 'px'
    cursorGlow.value.style.top = e.clientY + 'px'
  }
}

function queueRevealScan() {
  nextTick(() => {
    observeRevealElements()
    setTimeout(observeRevealElements, 80)
  })
}

function observeRevealElements() {
  if (!observer) return

  document.querySelectorAll('.reveal').forEach((el) => {
    if (el.classList.contains('visible')) return
    observer.observe(el)
  })
}

onMounted(() => {
  window.addEventListener('mousemove', handleMouseMove)

  observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible')
        observer?.unobserve(entry.target)
      }
    })
  }, { threshold: 0.1 })

  queueRevealScan()
})

watch(
  () => route.fullPath,
  () => {
    queueRevealScan()
  }
)

onUnmounted(() => {
  window.removeEventListener('mousemove', handleMouseMove)
  observer?.disconnect()
})
</script>
